[deps]
AMDGPU = "21141c5a-9bdb-4563-92ae-f87d6854732e"
Ark = "56664e29-41e4-4ea5-ab0e-825499acc647"
BiotSavartBCs = "ec5a6caf-bdf7-41d0-b8e1-5fafde84e19f"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
ComputePipeline = "95dc2771-c249-4cd0-9c9f-1f3b4330693c"
Extents = "411431e0-e8b7-467b-b5e0-f676ba4f2910"
FFMPEG_jll = "b22a6f82-2f65-5046-a5b2-351ab43fb4e5"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
GLTF = "aeeaf58c-ab4d-11e9-3a9f-9b6bf58b4bc3"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Geant4 = "559df036-b7a0-42fd-85df-7d5dd9d70f44"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Hikari = "afc56b53-c9a9-482a-a956-d1d800e05558"
ImageShow = "4e3cecfd-b093-5904-9786-8bbb286a6a31"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
MapTiles = "fea52e5a-b371-463b-85f5-81770daa2737"
MeshIO = "7269a6da-0436-5bbc-96c2-40638cbb6118"
PlantGeom = "5edaa67e-25db-4eb9-bf81-05d793b2238d"
ProtPlot = "77b3afcc-388a-4e14-926d-b99c82d1a01f"
ProteinChains = "b8e8f2a5-48d3-44f1-ba0d-c71cb7726ff8"
Raycore = "afc56b53-c9a9-482a-a956-d1d800e05559"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
RayMakie = "70852e3a-d594-4041-8350-783a02753e02"
Tyler = "e170d443-b9d6-418a-9ee8-061e966341ef"
WaterLily = "ed894a53-35f9-47f1-b17f-85db9237eebd"
XPalm = "6b523e1e-d512-416c-8e51-a8fbef0064e7"

[sources]
Hikari = {url = "https://github.com/JuliaGraphics/Hikari.jl", rev = "sd/raycore-refactor"}
Raycore = {url = "https://github.com/JuliaGeometry/Raycore.jl", rev = "sd/multitype-vec"}
Makie = {url = "https://github.com/MakieOrg/Makie.jl.git", rev = "sd/hikari", subdir = "Makie"}
GLMakie = {url = "https://github.com/MakieOrg/Makie.jl.git", rev = "sd/hikari", subdir = "GLMakie"}
RayMakie = {url = "https://github.com/MakieOrg/Makie.jl.git", rev = "sd/hikari", subdir = "RayMakie"}
ComputePipeline = {url = "https://github.com/MakieOrg/Makie.jl.git", rev = "sd/hikari", subdir = "ComputePipeline"}
ProtPlot = {url = "https://github.com/SimonDanisch/ProtPlot.jl.git", rev = "sd/merge-ribbons"}
